"""empty message

Revision ID: 090092e13bc2
Revises: f89b2e8466e6
Create Date: 2024-11-19 14:27:10.098712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090092e13bc2'
down_revision = 'f89b2e8466e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
